"""Add player_potion_used_this_battle to CombatSession

Revision ID: 0d0d2f5c17db
Revises: ea824ed5db49
Create Date: 2026-09-17 18:25:02.087353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0d2f5c17db'
down_revision: Union[str, Sequence[str], None] = 'ea824ed5db49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default нужен вручную (см. ea824ed5db49) — таблица не пустая.
    op.add_column(
        'combat_sessions',
        sa.Column('player_potion_used_this_battle', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('combat_sessions', 'player_potion_used_this_battle')
    # ### end Alembic commands ###
