"""Add stat_allocation_log table

Revision ID: 2478b4a04630
Revises: 4c531d0ec03b
Create Date: 2026-09-17 11:24:53.880582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2478b4a04630'
down_revision: Union[str, Sequence[str], None] = '4c531d0ec03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_allocation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('level_at_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_allocation_log_character_id'), 'stat_allocation_log', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stat_allocation_log_character_id'), table_name='stat_allocation_log')
    op.drop_table('stat_allocation_log')
    # ### end Alembic commands ###
