"""initial schema

Revision ID: 4c531d0ec03b
Revises: 
Create Date: 2026-09-16 15:17:55.954234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c531d0ec03b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('victory_points', sa.Integer(), nullable=False),
    sa.Column('unspent_stat_points', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('vitality', sa.Integer(), nullable=False),
    sa.Column('hp_current', sa.Float(), nullable=False),
    sa.Column('last_hp_update_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_telegram_user_id'), 'characters', ['telegram_user_id'], unique=True)
    op.create_table('combat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('enemy_type', sa.String(), nullable=False),
    sa.Column('enemy_hp_current', sa.Float(), nullable=False),
    sa.Column('character_hp_snapshot', sa.Float(), nullable=False),
    sa.Column('current_turn', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('circumstance_outcome', sa.String(), nullable=True),
    sa.Column('circumstance_roller', sa.String(), nullable=True),
    sa.Column('strength_modifier_player', sa.Float(), nullable=False),
    sa.Column('strength_modifier_enemy', sa.Float(), nullable=False),
    sa.Column('player_flee_right_used', sa.Boolean(), nullable=False),
    sa.Column('enemy_flee_right_used', sa.Boolean(), nullable=False),
    sa.Column('turn_log', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_sessions_character_id'), 'combat_sessions', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combat_sessions_character_id'), table_name='combat_sessions')
    op.drop_table('combat_sessions')
    op.drop_index(op.f('ix_characters_telegram_user_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
