"""Add gold, loot, and potion inventory to Character

Revision ID: ea824ed5db49
Revises: 2478b4a04630
Create Date: 2026-09-17 16:43:55.355688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea824ed5db49'
down_revision: Union[str, Sequence[str], None] = '2478b4a04630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default нужен вручную (автоген его не проставляет) — таблица
    # уже не пустая (плейтест), SQLite не разрешает добавить NOT NULL
    # колонку без значения по умолчанию для существующих строк.
    op.add_column('characters', sa.Column('gold', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('characters', sa.Column('loot', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('characters', sa.Column('potions_small', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('characters', sa.Column('potions_large', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'potions_large')
    op.drop_column('characters', 'potions_small')
    op.drop_column('characters', 'loot')
    op.drop_column('characters', 'gold')
    # ### end Alembic commands ###
